/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Algorithm } from "./Algorithm";
import { AlgorithmCountArgs } from "./AlgorithmCountArgs";
import { AlgorithmFindManyArgs } from "./AlgorithmFindManyArgs";
import { AlgorithmFindUniqueArgs } from "./AlgorithmFindUniqueArgs";
import { DeleteAlgorithmArgs } from "./DeleteAlgorithmArgs";
import { AlgorithmService } from "../algorithm.service";
@graphql.Resolver(() => Algorithm)
export class AlgorithmResolverBase {
  constructor(protected readonly service: AlgorithmService) {}

  async _algorithmsMeta(
    @graphql.Args() args: AlgorithmCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Algorithm])
  async algorithms(
    @graphql.Args() args: AlgorithmFindManyArgs
  ): Promise<Algorithm[]> {
    return this.service.algorithms(args);
  }

  @graphql.Query(() => Algorithm, { nullable: true })
  async algorithm(
    @graphql.Args() args: AlgorithmFindUniqueArgs
  ): Promise<Algorithm | null> {
    const result = await this.service.algorithm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Algorithm)
  async deleteAlgorithm(
    @graphql.Args() args: DeleteAlgorithmArgs
  ): Promise<Algorithm | null> {
    try {
      return await this.service.deleteAlgorithm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
