/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Visualization as PrismaVisualization } from "@prisma/client";

export class VisualizationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VisualizationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.visualization.count(args);
  }

  async visualizations(
    args: Prisma.VisualizationFindManyArgs
  ): Promise<PrismaVisualization[]> {
    return this.prisma.visualization.findMany(args);
  }
  async visualization(
    args: Prisma.VisualizationFindUniqueArgs
  ): Promise<PrismaVisualization | null> {
    return this.prisma.visualization.findUnique(args);
  }
  async createVisualization(
    args: Prisma.VisualizationCreateArgs
  ): Promise<PrismaVisualization> {
    return this.prisma.visualization.create(args);
  }
  async updateVisualization(
    args: Prisma.VisualizationUpdateArgs
  ): Promise<PrismaVisualization> {
    return this.prisma.visualization.update(args);
  }
  async deleteVisualization(
    args: Prisma.VisualizationDeleteArgs
  ): Promise<PrismaVisualization> {
    return this.prisma.visualization.delete(args);
  }
}
