/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { NetworkTraffic } from "./NetworkTraffic";
import { NetworkTrafficCountArgs } from "./NetworkTrafficCountArgs";
import { NetworkTrafficFindManyArgs } from "./NetworkTrafficFindManyArgs";
import { NetworkTrafficFindUniqueArgs } from "./NetworkTrafficFindUniqueArgs";
import { DeleteNetworkTrafficArgs } from "./DeleteNetworkTrafficArgs";
import { NetworkTrafficService } from "../networkTraffic.service";
@graphql.Resolver(() => NetworkTraffic)
export class NetworkTrafficResolverBase {
  constructor(protected readonly service: NetworkTrafficService) {}

  async _networkTrafficsMeta(
    @graphql.Args() args: NetworkTrafficCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [NetworkTraffic])
  async networkTraffics(
    @graphql.Args() args: NetworkTrafficFindManyArgs
  ): Promise<NetworkTraffic[]> {
    return this.service.networkTraffics(args);
  }

  @graphql.Query(() => NetworkTraffic, { nullable: true })
  async networkTraffic(
    @graphql.Args() args: NetworkTrafficFindUniqueArgs
  ): Promise<NetworkTraffic | null> {
    const result = await this.service.networkTraffic(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NetworkTraffic)
  async deleteNetworkTraffic(
    @graphql.Args() args: DeleteNetworkTrafficArgs
  ): Promise<NetworkTraffic | null> {
    try {
      return await this.service.deleteNetworkTraffic(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
